import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { getLanguagePreference, setLanguagePreference } from "../lib/storage";

const translations = {
  "Hindi (Hindi)": {
    "CafeFlow": "कैफेफ्लो",
    "AI-Powered": "एआई संचालित",
    "Home": "होम",
    "Browse": "ब्राउज़",
    "Rewards": "रिवॉर्ड्स",
    "Track": "ट्रैक",
    "Analytics": "एनालिटिक्स",
    "Profile": "प्रोफाइल",
    "Your Perfect Meal, Just a Chat Away": "आपका परफेक्ट मील, बस एक चैट दूर",
    "Smart recommendations, exclusive deals, and rewards with every order.": "स्मार्ट सुझाव, खास डील्स और हर ऑर्डर पर रिवॉर्ड्स।",
    "Explore Now": "अभी देखें",
    "Order Usual": "फिर से ऑर्डर करें",
    "Reward Points": "रिवॉर्ड पॉइंट्स",
    "Orders": "ऑर्डर्स",
    "Special Offers": "स्पेशल ऑफर्स",
    "Crazy Deals": "क्रेज़ी डील्स",
    "First Order Special": "पहला ऑर्डर स्पेशल",
    "New users get 50% OFF + Free Delivery": "नए यूज़र्स को 50% छूट + फ्री डिलीवरी",
    "Flash Deal!": "फ्लैश डील!",
    "Get flat 30% OFF on orders above Rs500": "Rs500 से ऊपर के ऑर्डर पर 30% छूट",
    "Loyalty Rewards": "लॉयल्टी रिवॉर्ड्स",
    "Redeem 500 points for Rs200 OFF": "500 पॉइंट्स पर Rs200 छूट पाएं",
    "Weekend Bonanza": "वीकेंड बोनस",
    "Buy 1 Get 1 FREE on all beverages": "सभी बेवरेज पर 1 खरीदें 1 फ्री पाएं",
    "Popular Categories": "लोकप्रिय कैटेगरी",
    "Coffee & Tea": "कॉफी और चाय",
    "Fast Food": "फास्ट फूड",
    "Desserts": "डेज़र्ट्स",
    "Healthy": "हेल्दी",
    "Featured Picks": "फीचर्ड पिक्स",
    "Top restaurants ready when you are": "आपके लिए तैयार बेहतरीन रेस्टोरेंट",
    "Open now": "अभी खुला है",
    "Closed": "बंद",
    "Edit Profile": "प्रोफाइल संपादित करें",
    "Close": "बंद करें",
    "Cancel": "रद्द करें",
    "Save Profile": "प्रोफाइल सेव करें",
    "Your Usual Order": "आपका सामान्य ऑर्डर",
    "Favorite Items": "पसंदीदा आइटम्स",
    "Reorder Now": "फिर ऑर्डर करें",
    "Order History": "ऑर्डर हिस्ट्री",
    "Settings": "सेटिंग्स",
    "Notifications": "नोटिफिकेशन्स",
    "Saved Addresses": "सेव किए गए पते",
    "App Preferences": "ऐप प्रेफरेंसेस",
    "Logout": "लॉगआउट",
    "What to notify": "क्या सूचित करना है",
    "How to notify": "कैसे सूचित करना है",
    "Order Updates": "ऑर्डर अपडेट्स",
    "Track your order status": "अपने ऑर्डर की स्थिति ट्रैक करें",
    "Deals & Offers": "डील्स और ऑफर्स",
    "Get notified about new deals": "नई डील्स की सूचना पाएं",
    "Recommendations": "सुझाव",
    "AI-powered suggestions": "एआई आधारित सुझाव",
    "Points and achievements": "पॉइंट्स और उपलब्धियां",
    "Push Notifications": "पुश नोटिफिकेशन्स",
    "In-app alerts": "ऐप के अंदर अलर्ट",
    "SMS": "एसएमएस",
    "Text messages": "टेक्स्ट संदेश",
    "Email": "ईमेल",
    "Email updates": "ईमेल अपडेट्स",
    "Save Preferences": "प्रेफरेंसेस सेव करें",
    "Add New Address": "नया पता जोड़ें",
    "Default": "डिफॉल्ट",
    "Set as Default": "डिफॉल्ट बनाएं",
    "Edit": "संपादित करें",
    "Delete": "हटाएं",
    "Add Address": "पता जोड़ें",
    "Edit Address": "पता संपादित करें",
    "Label": "लेबल",
    "Address line": "पते की लाइन",
    "City": "शहर",
    "Pincode": "पिनकोड",
    "Set as default address": "इसे डिफॉल्ट पता बनाएं",
    "Save Address": "पता सेव करें",
    "Language": "भाषा",
    "App Settings": "ऐप सेटिंग्स",
    "Auto-play Videos": "ऑटो-प्ले वीडियो",
    "Auto-play deal videos": "डील वीडियो अपने आप चलें",
    "Haptic Feedback": "हैप्टिक फीडबैक",
    "Vibration on interactions": "इंटरैक्शन पर वाइब्रेशन",
    "Reduced Motion": "कम मोशन",
    "Minimize animations": "एनिमेशन कम करें",
    "Data Saver": "डेटा सेवर",
    "Reduce data usage": "डेटा उपयोग कम करें",
    "Cache Size": "कैश आकार",
    "Clear Cache": "कैश साफ करें",
    "Welcome back": "वापस स्वागत है",
    "Sign in and continue the experience.": "साइन इन करें और अनुभव जारी रखें।",
    "Public entry": "पब्लिक एंट्री",
    "Explore page before auth": "ऑथ से पहले एक्सप्लोर पेज",
    "After login": "लॉगिन के बाद",
    "Marketplace, menu, cart, booking, tracking": "मार्केटप्लेस, मेनू, कार्ट, बुकिंग, ट्रैकिंग",
    "Account access": "अकाउंट एक्सेस",
    "Sign in to CafeFlow": "CafeFlow में साइन इन करें",
    "Use your email and password to continue.": "जारी रखने के लिए अपना ईमेल और पासवर्ड उपयोग करें।",
    "Password": "पासवर्ड",
    "Enter your email": "अपना ईमेल दर्ज करें",
    "Enter your password": "अपना पासवर्ड दर्ज करें",
    "Sign in": "साइन इन",
    "Need an account?": "अकाउंट चाहिए?",
    "Register": "रजिस्टर",
    "Create account": "अकाउंट बनाएं",
    "Join the app and unlock the full flow.": "ऐप से जुड़ें और पूरा फ्लो अनलॉक करें।",
    "Included": "शामिल",
    "Restaurant discovery and Indian menu ordering": "रेस्टोरेंट खोज और भारतीय मेनू ऑर्डरिंग",
    "Also included": "साथ में",
    "Table booking, payments, delivery, live tracking": "टेबल बुकिंग, पेमेंट्स, डिलीवरी, लाइव ट्रैकिंग",
    "New account": "नया अकाउंट",
    "Register for CafeFlow": "CafeFlow के लिए रजिस्टर करें",
    "Enter your details to continue into the main app.": "मुख्य ऐप में जाने के लिए अपनी डिटेल्स दर्ज करें।",
    "Full name": "पूरा नाम",
    "Enter your full name": "अपना पूरा नाम दर्ज करें",
    "Create a password": "एक पासवर्ड बनाएं",
    "Already registered?": "पहले से रजिस्टर्ड हैं?",
    "Profile updated": "प्रोफाइल अपडेट हुई",
    "Your profile details were saved successfully.": "आपकी प्रोफाइल डिटेल्स सफलतापूर्वक सेव हुईं।",
    "Address saved": "पता सेव हुआ",
    "Address deleted": "पता हटाया गया",
    "The saved address has been removed.": "सेव किया गया पता हटा दिया गया है।",
    "Default changed": "डिफॉल्ट बदला गया",
    "Your default address was updated.": "आपका डिफॉल्ट पता अपडेट हो गया।",
    "Notifications saved": "नोटिफिकेशन सेव हुए",
    "Your notification preferences were updated.": "आपकी नोटिफिकेशन प्रेफरेंसेस अपडेट हुईं।",
    "Preferences saved": "प्रेफरेंसेस सेव हुईं",
    "App preferences have been updated.": "ऐप प्रेफरेंसेस अपडेट हो गईं।",
    "Cache cleared": "कैश साफ हुआ",
    "128.5 MB freed up.": "128.5 MB खाली हुआ।",
  },
  "Telugu (Telugu)": {
    "CafeFlow": "కేఫ్‌ఫ్లో",
    "AI-Powered": "ఏఐ ఆధారితం",
    "Home": "హోమ్",
    "Browse": "బ్రౌజ్",
    "Rewards": "రివార్డ్స్",
    "Track": "ట్రాక్",
    "Analytics": "అనలిటిక్స్",
    "Profile": "ప్రొఫైల్",
    "Saved Addresses": "సేవ్ చేసిన చిరునామాలు",
    "Notifications": "నోటిఫికేషన్స్",
    "App Preferences": "యాప్ ప్రిఫరెన్సెస్",
    "Settings": "సెట్టింగ్స్",
    "Logout": "లాగ్ అవుట్",
    "Save Preferences": "ప్రిఫరెన్సెస్ సేవ్ చేయండి",
    "Language": "భాష",
    "Clear Cache": "క్యాష్ క్లియర్ చేయండి",
  },
  "Tamil (Tamil)": {
    "CafeFlow": "கஃபேஃப்ளோ",
    "AI-Powered": "ஏஐ இயக்கம்",
    "Home": "முகப்பு",
    "Browse": "உலாவு",
    "Rewards": "வெகுமதிகள்",
    "Track": "கண்காணி",
    "Analytics": "பகுப்பாய்வு",
    "Profile": "சுயவிவரம்",
    "Saved Addresses": "சேமித்த முகவரிகள்",
    "Notifications": "அறிவிப்புகள்",
    "App Preferences": "ஆப் விருப்பங்கள்",
    "Settings": "அமைப்புகள்",
    "Logout": "வெளியேறு",
    "Save Preferences": "விருப்பங்களை சேமிக்கவும்",
    "Language": "மொழி",
    "Clear Cache": "கேஷ் அழிக்கவும்",
  },
  "Kannada (Kannada)": {
    "CafeFlow": "ಕಫೆಫ್ಲೋ",
    "AI-Powered": "ಎಐ ಚಾಲಿತ",
    "Home": "ಮುಖಪುಟ",
    "Browse": "ಬ್ರೌಸ್",
    "Rewards": "ರಿವಾರ್ಡ್ಸ್",
    "Track": "ಟ್ರ್ಯಾಕ್",
    "Analytics": "ಅನಾಲಿಟಿಕ್ಸ್",
    "Profile": "ಪ್ರೊಫೈಲ್",
    "Saved Addresses": "ಉಳಿಸಿದ ವಿಳಾಸಗಳು",
    "Notifications": "ಅಧಿಸೂಚನೆಗಳು",
    "App Preferences": "ಆಪ್ ಆದ್ಯತೆಗಳು",
    "Settings": "ಸೆಟ್ಟಿಂಗ್ಸ್",
    "Logout": "ಲಾಗ್‌ಔಟ್",
    "Save Preferences": "ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಿ",
    "Language": "ಭಾಷೆ",
    "Clear Cache": "ಕ್ಯಾಶ್ ತೆರವುಗೊಳಿಸಿ",
  },
  "Bengali (Bangla)": {
    "CafeFlow": "ক্যাফেফ্লো",
    "AI-Powered": "এআই চালিত",
    "Home": "হোম",
    "Browse": "ব্রাউজ",
    "Rewards": "রিওয়ার্ডস",
    "Track": "ট্র্যাক",
    "Analytics": "অ্যানালিটিক্স",
    "Profile": "প্রোফাইল",
    "Saved Addresses": "সেভ করা ঠিকানা",
    "Notifications": "নোটিফিকেশন",
    "App Preferences": "অ্যাপ পছন্দসমূহ",
    "Settings": "সেটিংস",
    "Logout": "লগআউট",
    "Save Preferences": "পছন্দ সংরক্ষণ করুন",
    "Language": "ভাষা",
    "Clear Cache": "ক্যাশ পরিষ্কার করুন",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getLanguagePreference);

  useEffect(() => {
    setLanguagePreference(language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (text) => translations[language]?.[text] || text,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
}
